import type { MediaAsset } from '@/content/destinations/types';

type PhotoInput = {
  file: string;
  alt: string;
  place: string;
  photographer: string;
  sourceId: string;
  width: number;
  height: number;
  objectPosition?: string;
  objectPositionMobile?: string;
};

function unsplash(input: PhotoInput): MediaAsset {
  return {
    src: `/images/discovery/${input.file}`,
    alt: input.alt,
    credit: `${input.place} · ${input.photographer} / Unsplash`,
    photographer: input.photographer,
    source: 'unsplash',
    sourceId: input.sourceId,
    sourceUrl: `https://unsplash.com/photos/${input.sourceId}`,
    licence: 'Unsplash',
    width: input.width,
    height: input.height,
    objectPosition: input.objectPosition ?? '50% 50%',
    objectPositionMobile: input.objectPositionMobile,
  };
}

/** Verified Unsplash frames from the Discovery/Destination mock-up. */
export const MEDIA = {
  heroDhermi: unsplash({
    file: 'big_hero_dhermi.jpg',
    alt: 'Turquoise water en rotsen aan het strand van Dhërmi, Albanese Rivièra',
    place: 'Dhërmi',
    photographer: 'Jani Godari',
    sourceId: 'LWEnGk29hAk',
    width: 1700,
    height: 1275,
    objectPosition: '50% 62%',
    objectPositionMobile: '42% 50%',
  }),
  dhermi: unsplash({
    file: 'dhermi.jpg',
    alt: 'Turquoise water en rotsen aan het strand van Dhërmi, Albanese Rivièra',
    place: 'Dhërmi',
    photographer: 'Jani Godari',
    sourceId: 'LWEnGk29hAk',
    width: 1000,
    height: 666,
    objectPosition: '50% 60%',
  }),
  vunoChapter: unsplash({
    file: 'big_vuno.jpg',
    alt: 'Vuno: witte huizen tegen de groene helling boven de Ionische Zee',
    place: 'Vuno',
    photographer: 'Marie Volkert',
    sourceId: '2RCAwZDiSqk',
    width: 1700,
    height: 1131,
    objectPosition: '62% 50%',
    objectPositionMobile: '68% 50%',
  }),
  vuno: unsplash({
    file: 'vuno.jpg',
    alt: 'Vuno, Albanië',
    place: 'Vuno',
    photographer: 'Marie Volkert',
    sourceId: '2RCAwZDiSqk',
    width: 1000,
    height: 666,
  }),
  sarandeChapter: unsplash({
    file: 'big_sarande.jpg',
    alt: 'Luchtfoto van de baai van Sarandë met de stad langs het water',
    place: 'Sarandë',
    photographer: 'Karol Chomka',
    sourceId: 'JrnMqKyyoHw',
    width: 1700,
    height: 957,
    objectPosition: '58% 50%',
    objectPositionMobile: '60% 50%',
  }),
  sarande: unsplash({
    file: 'sarande.jpg',
    alt: 'Sarandë',
    place: 'Sarandë',
    photographer: 'Karol Chomka',
    sourceId: 'JrnMqKyyoHw',
    width: 928,
    height: 619,
  }),
  gjiroChapter: unsplash({
    file: 'big_gjiro.jpg',
    alt: 'Gjirokastër: stenen torenhuizen tegen de groene helling',
    place: 'Gjirokastër',
    photographer: 'Adventure Albania',
    sourceId: 'Kqr2Mt_jIus',
    width: 1700,
    height: 1275,
    objectPosition: '60% 50%',
    objectPositionMobile: '62% 50%',
  }),
  gjiro: unsplash({
    file: 'gjiro.jpg',
    alt: 'Gjirokastër',
    place: 'Gjirokastër',
    photographer: 'Adventure Albania',
    sourceId: 'Kqr2Mt_jIus',
    width: 1000,
    height: 666,
  }),
  gjiroBazaar: unsplash({
    file: 'gjiro_bazaar.jpg',
    alt: 'Gjirokastër, Albanië',
    place: 'Gjirokastër',
    photographer: 'Adventure Albania',
    sourceId: 'hYsQP88bMlo',
    width: 1000,
    height: 666,
  }),
  thethChapter: unsplash({
    file: 'big_theth.jpg',
    alt: 'Het stenen kerkje van Theth voor de toppen van de Albanese Alpen',
    place: 'Theth',
    photographer: 'Adventure Albania',
    sourceId: '5ThW2r9pl0A',
    width: 1700,
    height: 1275,
    objectPosition: '35% 50%',
    objectPositionMobile: '22% 50%',
  }),
  theth: unsplash({
    file: 'theth.jpg',
    alt: 'Kerkje van Theth voor de toppen van de Albanese Alpen',
    place: 'Theth',
    photographer: 'Adventure Albania',
    sourceId: '5ThW2r9pl0A',
    width: 1000,
    height: 666,
    objectPosition: '50% 45%',
  }),
  ksamilEnd: unsplash({
    file: 'big_ksamil_end.jpg',
    alt: 'Rustig strand met strandwachtpost in Ksamil',
    place: 'Ksamil',
    photographer: 'Vangel Dimo',
    sourceId: '9KuqI1Zxdxw',
    width: 1600,
    height: 1067,
    objectPosition: '72% 55%',
  }),
  ksamil: unsplash({
    file: 'ksamil.jpg',
    alt: 'Ksamil',
    place: 'Ksamil',
    photographer: 'Adventure Albania',
    sourceId: '8HKxepZ88i0',
    width: 1000,
    height: 666,
  }),
  himare: unsplash({
    file: 'himare.jpg',
    alt: 'Himarë',
    place: 'Himarë',
    photographer: 'Marie Volkert',
    sourceId: 'abHRwTf7N4I',
    width: 1000,
    height: 666,
  }),
  berat: unsplash({
    file: 'berat.jpg',
    alt: 'Berat',
    place: 'Berat',
    photographer: 'Vladan Raznatovic',
    sourceId: '_-cz1Bk5qZ0',
    width: 1000,
    height: 666,
  }),
  berat2: unsplash({
    file: 'berat2.jpg',
    alt: 'Berat, Albanië',
    place: 'Berat',
    photographer: 'Konpasu.de',
    sourceId: '3q-xGdVLcGA',
    width: 1000,
    height: 666,
  }),
  sardiniaCove: unsplash({
    file: 'cove_sardinia.jpg',
    alt: 'Verscholen zandbaai met helder water op Sardinië',
    place: 'Sardinië',
    photographer: 'Mitch Botsford',
    sourceId: '2VJKXUKNvDA',
    width: 1000,
    height: 666,
    objectPosition: '40% 50%',
  }),
  cefalu: unsplash({
    file: 'cefalu.jpg',
    alt: 'Cefalù met de rots La Rocca, Sicilië',
    place: 'Cefalù',
    photographer: 'Henrique Ferreira',
    sourceId: 'Er4gxPJpRe8',
    width: 1000,
    height: 666,
    objectPosition: '40% 50%',
  }),
  chania: unsplash({
    file: 'chania.jpg',
    alt: 'Kleurrijke gevels aan de oude haven van Chania, Kreta',
    place: 'Chania',
    photographer: 'Patrick Lalonde',
    sourceId: 'hFnhCw9Oots',
    width: 1000,
    height: 666,
  }),
  madeira: unsplash({
    file: 'madeira.jpg',
    alt: 'Groene kliffen aan de noordkust van Madeira',
    place: 'Noordkust Madeira',
    photographer: 'Colin Watts',
    sourceId: 'C8e3LGjg3fc',
    width: 1000,
    height: 666,
    objectPosition: '60% 50%',
  }),
  algarve: unsplash({
    file: 'algarve.jpg',
    alt: 'Houten wandelpad naar Praia da Bordeira, Algarve',
    place: 'Praia da Bordeira',
    photographer: 'Diego Gennaro',
    sourceId: 'cmYjQ30PbWk',
    width: 1000,
    height: 666,
    objectPosition: '55% 50%',
  }),
  ronda: unsplash({
    file: 'ronda.jpg',
    alt: 'Puente Nuevo in Ronda, Andalusië',
    place: 'Ronda',
    photographer: 'Bo Saldaña',
    sourceId: 'dFglhZpS9-8',
    width: 1100,
    height: 825,
    objectPosition: '55% 50%',
  }),
  frigiliana: unsplash({
    file: 'frigiliana.jpg',
    alt: 'Frigiliana, Andalusië',
    place: 'Frigiliana',
    photographer: 'Christian Hergesell',
    sourceId: 'Fn_WsWPmAMc',
    width: 1100,
    height: 825,
  }),
} as const;
